// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tttgame.proto

package pt.ulisboa.tecnico.distsys.ttt;

public interface CheckWinnerResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pt.ulisboa.tecnico.distsys.ttt.CheckWinnerResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 result = 1;</code>
   * @return The result.
   */
  int getResult();
}
