// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tttgame.proto

package pt.ulisboa.tecnico.distsys.ttt;

public interface InfoRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pt.ulisboa.tecnico.distsys.ttt.InfoRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 player = 1;</code>
   * @return The player.
   */
  int getPlayer();
}
