// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tttgame.proto

package pt.ulisboa.tecnico.distsys.ttt;

public final class Tttgame {
  private Tttgame() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pt_ulisboa_tecnico_distsys_ttt_CurrentBoardRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pt_ulisboa_tecnico_distsys_ttt_CurrentBoardRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pt_ulisboa_tecnico_distsys_ttt_CurrentBoardResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pt_ulisboa_tecnico_distsys_ttt_CurrentBoardResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pt_ulisboa_tecnico_distsys_ttt_PlayRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pt_ulisboa_tecnico_distsys_ttt_PlayRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pt_ulisboa_tecnico_distsys_ttt_PlayResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pt_ulisboa_tecnico_distsys_ttt_PlayResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pt_ulisboa_tecnico_distsys_ttt_CheckWinnerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pt_ulisboa_tecnico_distsys_ttt_CheckWinnerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pt_ulisboa_tecnico_distsys_ttt_CheckWinnerResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pt_ulisboa_tecnico_distsys_ttt_CheckWinnerResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pt_ulisboa_tecnico_distsys_ttt_InfoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pt_ulisboa_tecnico_distsys_ttt_InfoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pt_ulisboa_tecnico_distsys_ttt_InfoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pt_ulisboa_tecnico_distsys_ttt_InfoResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rtttgame.proto\022\036pt.ulisboa.tecnico.dist" +
      "sys.ttt\"\025\n\023CurrentBoardRequest\"%\n\024Curren" +
      "tBoardResponse\022\r\n\005board\030\001 \001(\t\":\n\013PlayReq" +
      "uest\022\013\n\003row\030\001 \001(\005\022\016\n\006column\030\002 \001(\005\022\016\n\006pla" +
      "yer\030\003 \001(\005\"J\n\014PlayResponse\022:\n\006result\030\001 \001(" +
      "\0162*.pt.ulisboa.tecnico.distsys.ttt.PlayR" +
      "esult\"\024\n\022CheckWinnerRequest\"%\n\023CheckWinn" +
      "erResponse\022\016\n\006result\030\001 \001(\005\"\035\n\013InfoReques" +
      "t\022\016\n\006player\030\001 \001(\005\"\035\n\014InfoResponse\022\r\n\005pla" +
      "ys\030\001 \001(\005*n\n\nPlayResult\022\013\n\007UNKNOWN\020\000\022\021\n\rO" +
      "UT_OF_BOUNDS\020\001\022\020\n\014SQUARE_TAKEN\020\002\022\016\n\nWRON" +
      "G_TURN\020\003\022\021\n\rGAME_FINISHED\020\004\022\013\n\007SUCCESS\020\005" +
      "2\276\003\n\003TTT\022y\n\014CurrentBoard\0223.pt.ulisboa.te" +
      "cnico.distsys.ttt.CurrentBoardRequest\0324." +
      "pt.ulisboa.tecnico.distsys.ttt.CurrentBo" +
      "ardResponse\022a\n\004Play\022+.pt.ulisboa.tecnico" +
      ".distsys.ttt.PlayRequest\032,.pt.ulisboa.te" +
      "cnico.distsys.ttt.PlayResponse\022v\n\013CheckW" +
      "inner\0222.pt.ulisboa.tecnico.distsys.ttt.C" +
      "heckWinnerRequest\0323.pt.ulisboa.tecnico.d" +
      "istsys.ttt.CheckWinnerResponse\022a\n\004Info\022+" +
      ".pt.ulisboa.tecnico.distsys.ttt.InfoRequ" +
      "est\032,.pt.ulisboa.tecnico.distsys.ttt.Inf" +
      "oResponseB\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_pt_ulisboa_tecnico_distsys_ttt_CurrentBoardRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pt_ulisboa_tecnico_distsys_ttt_CurrentBoardRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pt_ulisboa_tecnico_distsys_ttt_CurrentBoardRequest_descriptor,
        new java.lang.String[] { });
    internal_static_pt_ulisboa_tecnico_distsys_ttt_CurrentBoardResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_pt_ulisboa_tecnico_distsys_ttt_CurrentBoardResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pt_ulisboa_tecnico_distsys_ttt_CurrentBoardResponse_descriptor,
        new java.lang.String[] { "Board", });
    internal_static_pt_ulisboa_tecnico_distsys_ttt_PlayRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_pt_ulisboa_tecnico_distsys_ttt_PlayRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pt_ulisboa_tecnico_distsys_ttt_PlayRequest_descriptor,
        new java.lang.String[] { "Row", "Column", "Player", });
    internal_static_pt_ulisboa_tecnico_distsys_ttt_PlayResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_pt_ulisboa_tecnico_distsys_ttt_PlayResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pt_ulisboa_tecnico_distsys_ttt_PlayResponse_descriptor,
        new java.lang.String[] { "Result", });
    internal_static_pt_ulisboa_tecnico_distsys_ttt_CheckWinnerRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_pt_ulisboa_tecnico_distsys_ttt_CheckWinnerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pt_ulisboa_tecnico_distsys_ttt_CheckWinnerRequest_descriptor,
        new java.lang.String[] { });
    internal_static_pt_ulisboa_tecnico_distsys_ttt_CheckWinnerResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_pt_ulisboa_tecnico_distsys_ttt_CheckWinnerResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pt_ulisboa_tecnico_distsys_ttt_CheckWinnerResponse_descriptor,
        new java.lang.String[] { "Result", });
    internal_static_pt_ulisboa_tecnico_distsys_ttt_InfoRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_pt_ulisboa_tecnico_distsys_ttt_InfoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pt_ulisboa_tecnico_distsys_ttt_InfoRequest_descriptor,
        new java.lang.String[] { "Player", });
    internal_static_pt_ulisboa_tecnico_distsys_ttt_InfoResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_pt_ulisboa_tecnico_distsys_ttt_InfoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pt_ulisboa_tecnico_distsys_ttt_InfoResponse_descriptor,
        new java.lang.String[] { "Plays", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
